stages:
  - unit_tests
  - end_to_end_tests

test_metadata:
  stage: unit_tests
  image: golang:latest
  before_script:
    - cd code/OptiFS/filesystem/metadata
  script:
    - go test -v ./

test_permissions:
  stage: unit_tests
  image: golang:latest
  before_script:
    - cd code/OptiFS/filesystem/permissions
  script:
    - go test -v ./

test_hashing:
  stage: unit_tests
  image: golang:latest
  before_script:
    - cd code/OptiFS/filesystem/hashing
  script:
    - go test -v ./

test_filesystem:
  stage: end_to_end_tests
  image: golang:latest
  before_script:
    - cd code/OptiFS/filesystem
  script:
    - go test -v ./
